tasks:
  build:
    steps:
    - checkout
    - docker/build:
        image: my-ruby-app:latest

  rspec:
    runner:
      containers:
      - image: razorci/ruby:3.2.2
    steps:
    - checkout
    - cache/pull:
        key: bundle-{{ checksum "Gemfile.lock" }}

    - commands:
      - gem --version && ruby --version
      - gem install bundler:2.4.10
      - bundle --version

    - run: bundle install --path vendor/bundle || bundle check

    - commands:
      - bundle exec rake db:migrate
      - bundle exec rspec
    - cache/push:
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths: [vendor/bundle]

    - reports/html: 
        dir: coverage
        index: index.html
    - reports/junit:
      - rspec.xml

    - run: docker logs postgres
      when: on_fail
