tasks:
  build:
    steps:
    - checkout
    - docker/build:
        image: my-ruby-app:latest

  rspec:
    runner:
      containers:
      - image: ruby:3.2.2
       - image: postgres:9.6
        environment:
        - POSTGRES_DB=rails_sample_app_test
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=secret
        options:
        - --name=postgres
    steps:
    - checkout
    - cache/pull:
        key: bundle-{{ checksum "Gemfile.lock" }}

    - commands:
      - gem --version && ruby --version
      - gem install bundler:2.4.20
      - bundle --version

    - run: bundle install --path vendor/bundle || bundle check

    - commands:
      - docker run -p 3000:3000 my-ruby-app
    - cache/push:
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths: [vendor/bundle]

    - reports/html: 
        dir: coverage
        index: index.html
    - reports/junit:
      - rspec.xml

